modalidad_actividad = ("presencial", "virtual", "ambas")
sexo = ("mujer", "hombre")
disciplina_artesano = (
    "alfareria y ceramica",
    "cesteria",
    "canteria y piedras",
    "huesos-cuernos-conchas",
    "instrumentos musicales y luthier",
    "madera",
    "marroquineria y talabarteria (cueros)",
    "metales y orfebreria",
    "papel",
    "textileria",
    "vidrio",
    "otros",
)
vinculo = ("contrato", "externo")
tipo_mon_nac = (
    "monumento historico mueble",
    "monumento historico inmueble",
    "santuario de la naturaleza",
    "zona tipica",
)

tipo_pat_natural = ("Monumento natural", "parque nacional", "reserva nacional")

nivel_educacional = ("basica", "media")

pueblo_originario = (
    "Mapuche",
    "Aymara",
    "Rapa Nui",
    "Atacamenos",
    "Quechua",
    "Colla",
    "Chango",
    "Diaguita",
    "Kawesqar",
    "Yagan",
)

valores_ambito_patrimonio = [
    "Artes del espectáculo",
    "Conocimientos y usos relacionados con la naturaleza y el universo",
    "Técnicas Artesanales tradicionales",
    "Tradiciones y Expresiones Orales",
    "Usos sociales, rituales y actos festivos",
]

valores_patrimonio_inmaterial = [
    "Baile de morenos de paso en la región de Arica y Parinacota",
    "Tradición de las Cruces de Mayo afrodescendientes en los valles de Azapa, Lluta y Acha",
    "Baile de morenos de paso en la región de Arica y Parinacota",
    "Bailes chinos",
    "Danza cachimbo de las comunas de Pica, Huara y Pozo Almonte",
    "Baile de morenos de paso en la región de Arica y Parinacota",
    "Bailes chinos",
    "Bailes Devocionales de la Oficina Salitrera Pedro de Valdivia",
    "Bailes tradicionales de San Pedro de Atacama",
    "Conocimientos y técnicas de alfareras y alfareros de Santiago Río Grande",
    "Música carnavaleña y cuecas tradicionales de Toconao",
    "Teatro tradicional de títeres",
    "Bailes chinos",
    "Trashumancia Kolla",
    "Bailes chinos",
    "Canto a lo poeta",
    "Circo Tradicional en Chile",
    "Crianza caprina pastoril del río Choapa",
    "Teatro tradicional de títeres",
    "Trashumancia andina del Río Choapa Alto",
    "Bailes chinos",
    "Canto a lo poeta",
    "Circo Tradicional en Chile",
    "Kai Kai de Rapa Nui",
    "Música de la bohemia tradicional de Valparaíso",
    "Oficio tradicional del organillero-chinchinero",
    "Teatro tradicional de títeres",
    "Tradición de los dulces de La Ligua",
    "Tradición oral Rapa Nui",
    "Baile de los Negros de Lora",
    "Bailes chinos",
    "Canto a lo poeta",
    "Circo Tradicional en Chile",
    "Fiesta de Cuasimodo",
    "Minería de oro de Santa Celia",
    "Música de la bohemia tradicional de Valparaíso",
    "Oficio tradicional del organillero-chinchinero",
    "Portadores del anda de la Fiesta de la Virgen de la Merced de Isla de Maipo",
    "Teatro tradicional de títeres",
    "Técnica de la cuelcha o trenzado en fibra de trigo en el secano interior del Valle del Río Itata",
    "Canto a lo poeta",
    "Circo Tradicional en Chile",
    "Modo de vida campesino de Larmahue y su vinculación con el medioambiente a través de las ruedas de agua",
    "Tradición de salineros y salineras en Cáhuil, Barrancas, La Villa, Lo Valdivia y Yoncavén",
    "Trenzadoras y trenzadores de paja de trigo ligún en la localidad de Cutemu y alrededores, en la comuna de Paredones, región de O"
    "Higgins",
    "Baile de los Negros de Lora",
    "Canto a lo poeta",
    "Circo Tradicional en Chile",
    "Loceras de Pilén, comuna de Cauquenes, región del Maule",
    "Música de la bohemia tradicional de Valparaíso",
    "Teatro tradicional de títeres",
    "Tejido en Crin de Rari y Panimavida",
    "Tradición de salineros y salineras en Cáhuil, Barrancas, La Villa, Lo Valdivia y Yoncavén",
    "Alfarería de la quebrada de las Ulloa",
    "Alfarería de Quinchamalí y Santa Cruz de Cuca",
    "Canto a lo poeta",
    "Circo Tradicional en Chile",
    "Técnica de la cuelcha o trenzado en fibra de trigo en el secano interior del Valle del Río Itata",
    "Alfarería de la quebrada de las Ulloa",
    "Bailes chinos",
    "Canto a lo poeta",
    "Carpintería de ribera del Boca Lebu",
    "Circo Tradicional en Chile",
    "Componedores de huesos en Tirúa",
    "Conocimientos, saberes y prácticas de la comunidad de Caleta Tumbes asociados al rito fúnebre ante la desaparición de pescadores en el mar",
    "Fabricación y venta de tortillas de rescoldo de Laraquete",
    "Kimün trarikanmakuñ Wallmapu",
    "Recolección y ruta del cochayuyo desde los sectores Pilico, Casa de Piedra, Danquil y Quilantahue, hasta Temuco",
    "Representación del imaginario rural a través de bordados, forma de expresión de las mujeres de Copiulemu",
    "Teatro tradicional de títeres",
    "Técnicas y saberes asociados a la cestería de coirón y chupón en Hualqui",
    "Técnicas y saberes asociados a la práctica arriera y criancera de la cordillera de Antuco",
    "Técnicas y saberes asociados al pan minero de Lota",
    "Canto a lo poeta",
    "Circo Tradicional en Chile",
    "Kimün trarikanmakuñ Wallmapu",
    "Minería de oro de Santa Celia",
    "Recolección y ruta del cochayuyo desde los sectores Pilico, Casa de Piedra, Danquil y Quilantahue, hasta Temuco",
    "Teatro tradicional de títeres",
    "Canto a lo poeta",
    "Carpintería de ribera de Cutipay",
    "Circo Tradicional en Chile",
    "Artesanía chilota en fibra vegetal y sus diferentes tradiciones",
    "Bailes chinos",
    "Canto a lo poeta",
    "Carpintería de ribera tradicional en la región de Los Lagos",
    "Pasacalles devocionales de la cultura chilota",
    "Tejuelería en la región de Aysén",
    "Tradición de Fiscales de la cultura chilota",
    "Tradición del tejido en Quelgo",
    "Carpintería de Ribera en la región de Aysén",
    "Carpintería de ribera tradicional en la región de Los Lagos",
    "Fabricación y práctica de la taba patagónica",
    "Tejuelería en la región de Aysén",
    "Trabajo en soga en la región de Aysén",
    "Canto a lo poeta",
    "Carpintería de ribera en la región de Magallanes",
    "Cestería Yagan",
    "Circo Tradicional en Chile",
    "Modo de vida asociado a las labores del campo en Torres del Paine",
]
